(function(m){var w=navigator.userAgent.toLowerCase(),d=function(b){return b.test(w)},i=Object.prototype.toString,k=document.documentMode,x=d(/opera/);x&&d(/version\/10\.5/);var A=d(/\bchrome\b/),B=d(/webkit/),o=!A&&d(/safari/),J=o&&d(/applewebkit\/4/),K=o&&d(/version\/3/),L=o&&d(/version\/4/),r=!x&&d(/msie/),M=r&&(d(/msie 8/)&&7!=k&&9!=k||8==k),N=r&&(d(/msie 9/)&&7!=k&&8!=k||9==k);r&&d(/msie 10/);var O=!!document.createElement("canvas").getContext,s=!B&&d(/gecko/),y=s&&d(/rv:1\.9/),C=s&&d(/rv:2\.0/),
P=y&&d(/rv:1\.9\.1/),Q=y&&d(/rv:1\.9\.2/),R=C&&d(/rv:2\.0\.\d/),S=s&&d(/firefox/),T=d(/windows|win32/),U=d(/macintosh|mac os x/),V=d(/linux/),u={Linear:function(b,c,e,f){return e*b/f+c},Quad:{easeIn:function(b,c,e,f){return e*(b/=f)*b+c},easeOut:function(b,c,e,f){return-e*(b/=f)*(b-2)+c},easeInOut:function(b,c,e,f){return 1>(b/=f/2)?e/2*b*b+c:-e/2*(--b*(b-2)-1)+c}},Cubic:{easeIn:function(b,c,e,f){return e*(b/=f)*b*b+c},easeOut:function(b,c,e,f){return e*((b=b/f-1)*b*b+1)+c},easeInOut:function(b,c,
e,f){return 1>(b/=f/2)?e/2*b*b*b+c:e/2*((b-=2)*b*b+2)+c}},Quart:{easeIn:function(b,c,e,f){return e*(b/=f)*b*b*b+c},easeOut:function(b,c,e,f){return-e*((b=b/f-1)*b*b*b-1)+c},easeInOut:function(b,c,e,f){return 1>(b/=f/2)?e/2*b*b*b*b+c:-e/2*((b-=2)*b*b*b-2)+c}},Bounce:{easeOut:function(b,c,e,f){return(b/=f)<1/2.75?e*7.5625*b*b+c:b<2/2.75?e*(7.5625*(b-=1.5/2.75)*b+0.75)+c:b<2.5/2.75?e*(7.5625*(b-=2.25/2.75)*b+0.9375)+c:e*(7.5625*(b-=2.625/2.75)*b+0.984375)+c}}},W=Math.sin,X=Math.cos,D=2*Math.PI,Y=Math.ceil,
z=Math.round,Z=Math.floor,E=function(b,c){if(iChart.isNumber(b))return[b,b,b,b];b=b.trim().replace(/\s{2,}/g,/\s/).replace(/\s/g,",").split(",");1==b.length?b[0]=b[1]=b[2]=b[3]=parseFloat(b[0])||c:2==b.length?(b[0]=b[2]=parseFloat(b[0])||c,b[1]=b[3]=parseFloat(b[1])||c):3==b.length?(b[0]=parseFloat(b[0])||c,b[1]=b[3]=parseFloat(b[1])||c,b[2]=parseFloat(b[2])||c):(b[0]=parseFloat(b[0])||c,b[1]=parseFloat(b[1])||c,b[2]=parseFloat(b[2])||c,b[3]=parseFloat(b[3])||c);return b},F=function(b){if(0==b)return b;
for(var b=b/10,c=0;1>b;)b*=10,c++;for(;1<b/10;)b/=10,c--;for(b=Math.floor(b);0<c;)b/=10,c--;for(;0>c;)b*=10,c++;return b},$="navy,olive,silver,gold,lime,fuchsia,aqua,green,red,blue,pink,purple,yellow,maroon,black,gray,white".split(","),G={aqua:"rgb(0,255,255)",azure:"rgb(240,255,255)",beige:"rgb(245,245,220)",black:"rgb(0,0,0)",blue:"rgb(0,0,255)",brown:"rgb(165,42,42)",cyan:"rgb(0,255,255)",darkblue:"rgb(0,0,139)",darkcyan:"rgb(0,139,139)",darkgrey:"rgb(169,169,169)",darkgreen:"rgb(0,100,0)",darkkhaki:"rgb(189,183,107)",
darkmagenta:"rgb(139,0,139)",darkolivegreen:"rgb(85,107,47)",darkorange:"rgb(255,140,0)",darkorchid:"rgb(153,50,204)",darkred:"rgb(139,0,0)",darksalmon:"rgb(233,150,122)",darkviolet:"rgb(148,0,211)",fuchsia:"rgb(255,0,255)",gold:"rgb(255,215,0)",green:"rgb(0,128,0)",indigo:"rgb(75,0,130)",khaki:"rgb(240,230,140)",lightblue:"rgb(173,216,230)",lightcyan:"rgb(224,255,255)",lightgreen:"rgb(144,238,144)",lightgrey:"rgb(211,211,211)",lightpink:"rgb(255,182,193)",lightyellow:"rgb(255,255,224)",lime:"rgb(0,255,0)",
magenta:"rgb(255,0,255)",maroon:"rgb(128,0,0)",navy:"rgb(0,0,128)",olive:"rgb(128,128,0)",orange:"rgb(255,165,0)",pink:"rgb(255,192,203)",purple:"rgb(128,0,128)",violet:"rgb(128,0,128)",red:"rgb(255,0,0)",silver:"rgb(192,192,192)",white:"rgb(255,255,255)",yellow:"rgb(255,255,0)",transparent:"rgb(255,255,255)"},v=function(b,c){c=c||0.14;return 0.5<b?c-(1-b)/10:0.1<b?c-0.16+b/5:b>c?c:b/2},H=function(b,c,e,f){var c=iChart.Math.cToArray(iChart.Math.toRgb(c)),d=iChart.Math.toHsv(c);d[1]-=f||0;b?(d[2]-=
v(d[2],e),d[1]=iChart.Math.upTo(d[1],1),d[2]=iChart.Math.lowTo(d[2],0)):(d[2]+=v(1-d[2],e),d[1]=iChart.Math.lowTo(d[1],0),d[2]=iChart.Math.upTo(d[2],1));return iChart.Math.hsvToRgb(d,c[3])},I=function(b){var c=!1,d=!1,f=[],k=function(){if(document.addEventListener)return function(){document.removeEventListener("DOMContentLoaded",k,!1);n()};if(document.attachEvent)return function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",k),n())}}(),m=function(){if(!c){try{document.documentElement.doScroll("left")}catch(a){setTimeout(m,
1);return}n()}},n=function(){if(!c){c=!0;for(var a=0;a<f.length;a++)f[a].call(document);f=[]}},v=function(){if(!d){d=!0;if("complete"===document.readyState)return setTimeout(n,1);if(document.addEventListener)document.addEventListener("DOMContentLoaded",k,!1),b.addEventListener("load",n,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",k);b.attachEvent("onload",n);var a=!1;try{a=null==b.frameElement}catch(l){}document.documentElement.doScroll&&a&&m()}}},w=function(a){v();
c?a.call(document,g):f.push(function(){return a.call(this)})},g=function(a){if(!a||a.nodeType)return a;if("string"===typeof a)return-1!=a.indexOf("#")&&(a=a.substring(1)),document.getElementById(a);"function"===typeof a&&w(a)};g.apply=function(a,l){if(a&&l&&"object"==typeof l)for(var b in l)"undefined"!=typeof l[b]&&(a[b]=l[b]);if(!l&&a){var j={};for(b in a)j[b]=a[b];return j}return a};g.applyIf=function(a,l){if(a&&l&&"object"==typeof l)for(var b in l)"undefined"!=typeof l[b]&&"undefined"==typeof a[b]&&
(a[b]=l[b]);return!l&&a?g.apply(a):a};g.merge=function(a,b,h){if(a&&b&&"object"==typeof b){for(var j in b)"undefined"!=typeof b[j]&&("[object Object]"===i.apply(b[j])?"[object Object]"===i.apply(a[j])?g.merge(a[j],b[j]):a[j]=g.clone(b[j],!0):a[j]=b[j]);if("object"==typeof h)return g.merge(a,h)}return a};g.clone=function(a,b,h){var j={};if("[object Array]"===i.apply(a)&&"[object Object]"===i.apply(b))for(var c=0;c<a.length;c++)j[a[c]]=h&&"[object Object]"===i.apply(b[a[c]])?g.clone(b[a[c]]):b[a[c]];
else if("[object Object]"===i.apply(a))for(c in a)j[c]=b&&"[object Object]"===i.apply(a[c])&&!(a[c]instanceof g.Painter)?g.clone(a[c],b):a[c];return j};g.override=function(a,b){if(b){var h=a.prototype;g.apply(h,b);g.isIE&&b.hasOwnProperty("toString")&&(h.toString=b.toString)}};g.extend=function(){var a=function(a){for(var b in a)this[b]=a[b]},b=Object.prototype.constructor;return function(h,c){var d=function(){h.apply(this,arguments)},e=function(){},f=h.prototype;e.prototype=f;e=d.prototype=new e;
e.constructor=d;d.superclass=f;f.constructor==b&&(f.constructor=h);d.override=function(a){g.override(d,a)};e.superclass=e.supr=function(){return f};e.override=a;g.override(d,c);d.extend=function(a){return g.extend(d,a)};return d}}();g.apply(g,{version:"1.0",email:"wanghetommy@gmail.com",isEmpty:function(a,b){return null===a||void 0===a||g.isArray(a)&&!a.length||(!b?""===a:!1)},isArray:function(a){return"[object Array]"===i.apply(a)},isDate:function(a){return"[object Date]"===i.apply(a)},isObject:function(a){return!!a&&
"[object Object]"===i.apply(a)},isFunction:function(a){return"[object Function]"===i.apply(a)},isNumber:function(a){return"number"===typeof a&&isFinite(a)},isString:function(a){return"string"===typeof a},isBoolean:function(a){return"boolean"===typeof a},isFalse:function(a){return"boolean"===typeof a&&!a},isElement:function(a){return a?!!a.tagName:!1},isDefined:function(a){return"undefined"!==typeof a},getFont:function(a,b,h){return a+" "+b+"px "+h},getDoc:function(){return b.contentWindow?b.contentWindow.document:
b.contentDocument?b.contentDocument:b.document},DefineAbstract:function(a,b){if(!b[a])throw Error("Cannot instantiate the type '"+b.type+"'.you must implements it with method '"+a+"'.");},getAnimationArithmetic:function(a){return"linear"==a?u.Linear:"bounce"==a?u.Bounce.easeOut:"easeInOut"==a||"easeIn"==a||"easeOut"==a?u[g.DefaultAnimationArithmetic][a]:u.Linear},noConflict:function(){return I},emptyFn:function(){return!0},supportCanvas:O,isOpera:x,isWebKit:B,isChrome:A,isSafari:o,isSafari2:J,isSafari3:K,
isSafari4:L,isIE:r,isIE8:M,isIE9:N,isGecko:s,isGecko3:y,isGecko4:C,isFF:S,isFF3_5:P,isFF3_6:Q,isFF4:R,isLinux:V,isWindows:T,isMac:U,FRAME:20,INTERVAL:30,DefaultAnimationArithmetic:"Cubic"});g.Assert={gtZero:function(a,b){g.Assert.gt(a,0,b)},gt:function(a,b,h){if(!g.isNumber(a)&&a>=b)throw Error(h+" required a type Number gt "+b+",given:"+a);},isNumber:function(a,b){if(!g.isNumber(a))throw Error(b+" required a type Number,given:"+a);},isNotEmpty:function(a,b){if(!a||""==a)throw Error("it has required not empty.cause:"+
b);if(g.isArray(a)&&0==a.length)throw Error("required must has one element at least.cause:"+b);},isArray:function(a,b){if(!g.isArray(a))throw Error(b+" required a type Array,given:"+a);},isFunction:function(a,b){if(!g.isFunction(a))throw Error(b+" required a type Function,given:"+a);},isTrue:function(a,b){if(!0!==a)throw Error(b);},equal:function(a,b,h){if(a!==b)throw Error(h);}};g.Math={parseBorder:function(a,b){return E(a,b)},parsePadding:function(a,b){return E(a,b)},distanceP2P:function(a,b,h,
c){return Math.sqrt((h-a)*(h-a)+(c-b)*(c-b))},atanToAngle:function(a,b,h,c){if(a==h)return c>b?90:270;var d=g.Math.quadrant(a,b,h,c),a=g.Math.radianToAngle(Math.atan(Math.abs((b-c)/(a-h))));1==d?a=180-a:2==d?a=180+a:3==d&&(a=360-a);return a},atanToRadian:function(a,b,h,c){if(a==h)return c>b?Math.PI/2:3*Math.PI/2;var d=g.Math.quadrant(a,b,h,c),a=Math.atan(Math.abs((b-c)/(a-h)));1==d?a=Math.PI-a:2==d?a=Math.PI+a:3==d&&(a=2*Math.PI-a);return a},angleToRadian:function(a){return a*Math.PI/180},radianToAngle:function(a){return 180*
a/Math.PI},quadrant:function(a,b,h,c){return a<h?b<c?3:0:b<c?2:1},quadrantd:function(a){a=2*(a%(2*Math.PI));return Y(a/Math.PI)},upTo:function(a,b){return b>a?a:b},lowTo:function(a,b){return b<a?a:b},between:function(a,b,h){return g.Math.lowTo(a,g.Math.upTo(b,h))},inRange:function(a,b,h){return b>h&&a<h},angleInRange:function(a,b,h){a%=D;b%=D;return b>a?b>h&&a<h:b<a?h<b||h>a:h==b},inRangeClosed:function(a,b,h){return b>=h&&a<=h},inEllipse:function(a,b,h,c){return 1>=a*a/h/h+b*b/c/c},pToPoint:function(a,
b,c,d){return{x:a+X(c)*d,y:b+W(c)*d}},vectorP2P:function(a,b,c){c||(b=g.Math.angleToRadian(b),a=g.Math.angleToRadian(a));b=Math.sin(b);return{x:b*Math.sin(a),y:b*Math.cos(a)}},fixDeckle:function(a,b){return 1>=a?Math.floor(b)+0.5:Math.floor(b)},iGather:function(a){return(a||"magic")+"-"+(new Date).getTime().toString()},toPercent:function(a,b){return"("+(100*a).toFixed(b)+"%)"},parseFloat:function(a,b){if(!g.isNumber(a)&&(a=parseFloat(a),!g.isNumber(a)))throw Error("'"+b+"'is not a valid number.");
return a},ceil:function(a){return a+F(a)},floor:function(a){return a-F(a)},get:function(a){return $[a%16]},_2D:"2d",_3D:"3d",toRgb:function(a){a=a.replace(/\s/g,"").toLowerCase();if(/rgb\([0-9]{1,3},[0-9]{1,3},[0-9]{1,3}\)/.exec(a)||/rgba\([0-9]{1,3},[0-9]{1,3},[0-9]{1,3},(0(\.[0-9])?|1(\.0)?)\)/.exec(a))return a;if(/#(([a-fA-F0-9]{6})|([a-fA-F0-9]{3}))/.exec(a))return a=a.replace(/#/g,"").replace(/^(\w)(\w)(\w)$/,"$1$1$2$2$3$3"),"rgb("+parseInt(a.substring(0,2),16)+","+parseInt(a.substring(2,4),
16)+","+parseInt(a.substring(4,6),16)+")";if(G[a])return G[a];throw Error("invalid colors value '"+a+"'");},light:function(a,b,c){return H(!1,a,b,c)},dark:function(a,b,c){return H(!0,a,b,c)},cToArray:function(a){var b=/rgb\((\w*),(\w*),(\w*)\)/.exec(a);if(b)return[b[1],b[2],b[3]];if(b=/rgba\((\w*),(\w*),(\w*),(.*)\)/.exec(a))return[b[1],b[2],b[3],b[4]];throw Error("invalid colors value '"+a+"'");},toHsv:function(a,b,c){g.isArray(a)&&(b=a[1],c=a[2],a=a[0]);var a=a/255,b=b/255,c=c/255,d=Math.max(Math.max(a,
b),c),e=Math.min(Math.min(a,b),c),e=d-e;if(0==e)return[0,0,d];var f;a==d?f=(b-c)/e:b==d?f=(c-a)/e+2:c==d&&(f=(a-b)/e+4);f*=60;0>f&&(f+=360);return[f,e/d,d]},hsvToRgb:function(a,b,c,d){g.isArray(a)&&(d=b,b=a[1],c=a[2],a=a[0]);var e,f,i,k;k=Z(a/60)%6;a=a/60-k;p=c*(1-b);q=c*(1-b*a);t=c*(1-b*(1-a));switch(k){case 0:e=c;f=t;i=p;break;case 1:e=q;f=c;i=p;break;case 2:e=p;f=c;i=t;break;case 3:e=p;f=q;i=c;break;case 4:e=t;f=p;i=c;break;case 5:e=c,f=p,i=q}return"rgb"+(d?"a":"")+"("+z(255*e)+","+z(255*f)+","+
z(255*i)+(d?","+d+")":")")},fixPixel:function(a){return g.isNumber(a)?a:parseFloat(a.replace("px",""))||0},toPixel:function(a){return g.isNumber(a)?a+"px":g.Math.fixPixel(a)+"px"}};g.Event={addEvent:function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,d):a.attachEvent?a.attachEvent("on"+b,c):a["on"+b]=c},fix:function(a){"undefined"==typeof a&&(a=b.event);a.target||(a.target=a.srcElement||document);!a.relatedTarget&&a.fromElement&&(a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement);
if(null==a.pageX&&null!=a.clientX){var c=document.documentElement,d=document.body;a.pageX=a.clientX+(c&&c.scrollLeft||d&&d.scrollLeft||0)-(c&&c.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(c&&c.scrollTop||d&&d.scrollTop||0)-(c&&c.clientTop||d&&d.clientTop||0)}if("undefined"==typeof a.offsetX&&"undefined"==typeof a.offsetY&&"number"!=typeof a.offsetX){for(var d=c=0,e=a.target;e!=document.body&&e;)c+=e.offsetLeft,d+=e.offsetTop,e=e.offsetParent;a.offsetX=a.pageX-c;a.offsetY=a.pageY-d}if(null==
a.which&&(null!=a.charCode||null!=a.keyCode))a.which=null!=a.charCode?a.charCode:a.keyCode;!a.metaKey&&a.ctrlKey&&(a.metaKey=a.ctrlKey);!a.which&&void 0!==a.button&&(a.which=a.button&1?1:a.button&2?3:a.button&4?2:0);a.stopPropagation||(a.stopPropagation=function(){b.event.cancelBubble=true});return a}};return g}(m);String.prototype.trim||(String.prototype.trim=function(){return(this||"").replace(/^\s+|\s+$/g,"")});m.iChart=m.$=I})(window);
