(function(i){function w(a){"string"===typeof a&&(a=document.getElementById(a));if(!a||!a.tagName||"canvas"!=a.tagName.toLowerCase())throw Error("there not a canvas element");this.canvas=a;this.c=this.canvas.getContext("2d");this.width=this.canvas.width;this.height=this.canvas.height}var v=Math.PI/90,l=Math.PI,x=2*Math.PI,s=Math.sin,t=Math.cos,q=function(a,b){return 1>=a?Math.floor(b)+0.5:Math.floor(b)};w.prototype={css:function(a,b){if(i.isDefined(b))this.canvas.style[a]=b;else return this.canvas.style[a]},
arc:function(a,b,d,c,g,h,e,f,i,j,m,k,n,u,p,r,l){p=!!p;r=!!r;this.c.save();l&&(this.c.globalCompositeOperation="destination-over");e&&this.strokeStyle(f,i);this.shadowOn(j,m,k,n,u).fillStyle(h);this.c.moveTo(a,b);this.c.beginPath();this.c.arc(a,b,d,c,g,p);r&&this.c.lineTo(a,b);this.c.closePath();this.c.fill();e&&this.c.stroke();this.c.restore();return this},ellipse:function(a,b,d,c,g,h,e,f,i,j,m,k,n,u,p,r,l,q){r=!!r;l=!!l;this.c.save();q&&(this.c.globalCompositeOperation="destination-over");c&&this.strokeStyle(i,
j);this.shadowOn(m,k,n,u,p).fillStyle(e);this.c.moveTo(a,b);this.c.beginPath();for(l&&this.c.moveTo(a,b);g<=h;)this.c.lineTo(a+d*t(g),b+(r?-c*s(g):c*s(g))),g+=v;this.c.lineTo(a+d*t(h),b+(r?-c*s(h):c*s(h)));this.c.closePath();c&&this.c.stroke();this.c.fill();this.c.restore();return this},sector:function(a,b,d,c,g,h,e,f,i,j,m,k,n,u,p){j?(this.arc(a,b,d,c,g,h,e,f,i,j,m,k,n,u,p,!0),this.arc(a,b,d,c,g,h,e,f,i,!1,m,k,n,u,p,!0)):this.arc(a,b,d,c,g,h,e,f,i,!1,0,0,0,0,p,!0);return this},sector3D:function(){var a=
function(a,b,g,h,e,f,o,j,m){if(o&&f<=l||!o&&e>=l)return!1;var k=function(e,f){this.c.lineTo(a+g*t(e),b+(f||0)+(o?-h*s(e):h*s(e)))},e=o&&f>l&&e<l?l:e,f=!o&&e<l&&f>l?l:f,n=e;this.c.fillStyle=i.dark(m);this.c.moveTo(a+g*t(e),b+(o?-h*s(e):h*s(e)));for(this.c.beginPath();n<=f;)k.call(this,n),n+=v;k.call(this,f);this.c.lineTo(a+g*t(f),b+j+(o?-h*s(f):h*s(f)));for(n=f;n>=e;)k.call(this,n,j),n-=v;k.call(this,e,j);this.c.lineTo(a+g*t(e),b+(o?-h*s(e):h*s(e)));this.c.closePath();this.c.fill()},b=function(a,b,
g,h,e,f,o,j){this.c.moveTo(a,b);this.c.beginPath();this.c.fillStyle=i.dark(j);this.c.lineTo(a,b+f);g=a+g*t(o);h=b+f+(e?-h*s(o):h*s(o));this.c.lineTo(g,h);this.c.lineTo(g,h-f);this.c.lineTo(a,b);this.c.closePath();this.c.fill()};return function(d,c,g,h,e,f,o,j,m,k,n,u,p,r,q,s,t){u=u&&!i.isOpera;this.c.save();this.c.globalCompositeOperation="destination-over";this.c.fillStyle=j;var v=t?e<l/2||e>1.5*l:e>l/2&&e<1.5*l,w=t?f>l/2&&f<1.5*l:f<l/2||f>1.5*l;if(v||w)v&&b.call(this,d,c,g,h,t,o,e,j),w&&b.call(this,
d,c,g,h,t,o,f,j);this.ellipse(d,c+o,g,h,e,f,j,m,k,n,u,p,r,q,s,t,!0);this.c.globalCompositeOperation="source-over";this.ellipse(d,c,g,h,e,f,j,m,k,n,!1,p,r,q,s,t,!0);a.call(this,d,c,g,h,e,f,t,o,j);this.c.restore();return this}}(),textStyle:function(a,b,d){return this.textAlign(a).textBaseline(b).textFont(d)},strokeStyle:function(a,b,d){a&&(this.c.lineWidth=a);b&&(this.c.strokeStyle=b);d&&(this.c.lineJoin=d);return this},globalAlpha:function(a){a&&(this.c.globalAlpha=a);return this},fillStyle:function(a){a&&
(this.c.fillStyle=a);return this},textAlign:function(a){a&&(this.c.textAlign=a);return this},textBaseline:function(a){a&&(this.c.textBaseline=a);return this},textFont:function(a){a&&(this.c.font=a);return this},shadowOn:function(a,b,d,c,g){i.isString(a)&&(g=c,c=d,d=b,b=!0);a&&(this.c.shadowColor=b,this.c.shadowBlur=d,this.c.shadowOffsetX=c,this.c.shadowOffsetY=g);return this},shadowOff:function(){this.c.shadowColor="white";this.c.shadowBlur=this.c.shadowOffsetX=this.c.shadowOffsetY=0},avgLinearGradient:function(a,
b,d,c,g){a=this.createLinearGradient(a,b,d,c);for(b=0;b<g.length;b++)a.addColorStop(b/(g.length-1),g[b]);return a},createLinearGradient:function(a,b,d,c){return this.c.createLinearGradient(a,b,d,c)},avgRadialGradient:function(a,b,d,c,g,h,e){a=this.createRadialGradient(a,b,d,c,g,h);for(b=0;b<e.length;b++)a.addColorStop(b/(e.length-1),e[b]);return a},createRadialGradient:function(a,b,d,c,g,h){return this.c.createRadialGradient(a,b,d,c,g,h)},fillText:function(a,b,d,c,g,h,e){a+="";c=c||!1;h=h||"lr";e=
e||16;this.fillStyle(g);a=a.split("tb"==h?"":"\n");for(g=0;g<a.length;g++)c?this.c.fillText(a[g],b,d,c):this.c.fillText(a[g],b,d),d+=e;return this},measureText:function(a){return this.c.measureText(a).width},moveTo:function(a,b){this.c.moveTo(a||0,b||0);return this},lineTo:function(a,b){this.c.lineTo(a||0,b||0);return this},save:function(){this.c.save();return this},restore:function(){this.c.restore();return this},beginPath:function(){this.c.beginPath();return this},closePath:function(){this.c.closePath();
return this},stroke:function(){this.c.stroke();return this},fill:function(){this.c.fill();return this},text:function(a,b,d,c,g,h,e,f,i,j){this.c.save();this.textStyle(h,e,f);this.fillText(a,b,d,c,g,i,j);this.c.restore();return this},cube:function(a,b,d,c,g,h,e,f,o,j,m,k,n,l,p,r){a=q(j,a);b=q(j,b);e=e&&0<e?e:g;c=b-e*c;d=q(j,a+e*d);c=q(j,c);k&&(this.polygon(f,o,j,m,k,n,l,p,r,!1,[a,b,d,c,d+g,c,a+g,b]),this.polygon(f,o,j,m,k,n,l,p,r,!1,[a,b,a,b+h,a+g,b+h,a+g,b]),this.polygon(f,o,j,m,k,n,l,p,r,!1,[a+g,
b,d+g,c,d+g,c+h,a+g,b+h]));this.polygon(i.dark(f),o,j,m,!1,n,l,p,r,!1,[a,b,d,c,d+g,c,a+g,b]);this.polygon(f,o,j,m,!1,n,l,p,r,!1,[a,b,a,b+h,a+g,b+h,a+g,b]);this.polygon(i.dark(f),o,j,m,!1,n,l,p,r,!1,[a+g,b,d+g,c,d+g,c+h,a+g,b+h]);return this},cube3D:function(a,b,d,c,g,h,e,f,o,j,m,k){a=q(j,a);b=q(j,b);f=!f||0==f?h:f;g?(c=i.vectorP2P(d,c),d=a+f*c.x,c=b-f*c.y):(d=a+f*d,c=b-f*c);for(;6>k.length;)k.push(!1);d=q(j,d);c=q(j,c);f=[];0>c?i.isObject(k[4])&&f.push(i.applyIf({points:[a,b-e,d,c-e,d+h,c-e,a+h,b-
e]},k[4])):i.isObject(k[0])&&f.push(i.applyIf({points:[a,b,d,c,d+h,c,a+h,b]},k[0]));i.isObject(k[1])&&f.push(i.applyIf({points:[d,c,d,c-e,d+h,c-e,d+h,c]},k[1]));i.isObject(k[2])&&f.push(i.applyIf({points:[a,b,a,b-e,d,c-e,d,c]},k[2]));i.isObject(k[3])&&f.push(i.applyIf({points:[a+h,b,a+h,b-e,d+h,c-e,d+h,c]},k[3]));0>c?i.isObject(k[0])&&f.push(i.applyIf({points:[a,b,d,c,d+h,c,a+h,b]},k[0])):i.isObject(k[4])&&f.push(i.applyIf({points:[a,b-e,d,c-e,d+h,c-e,a+h,b-e]},k[4]));i.isObject(k[5])&&f.push(i.applyIf({points:[a,
b,a,b-e,a+h,b-e,a+h,b]},k[5]));for(a=0;a<f.length;a++)this.polygon(f[a].color,o,j,m,f[a].shadow,f[a].shadowColor,f[a].blur,f[a].sx,f[a].sy,f[a].alpha,f[a].points);return this},polygon:function(a,b,d,c,g,h,e,f,i,j,m){if(!(2>m.length)){this.c.save();this.strokeStyle(d,c);this.c.beginPath();this.fillStyle(a).globalAlpha(j).shadowOn(g,h,e,f,i).moveTo(m[0],m[1]);for(a=2;a<m.length;a+=2)this.lineTo(m[a],m[a+1]);this.c.closePath();b&&this.c.stroke();this.c.fill();this.c.restore();return this}},line:function(a,
b,d,c,g,h,e){if(!g||0==g)return this;this.c.save();e&&(this.c.globalCompositeOperation="destination-over");a=q(g,a);b=q(g,b);d=q(g,d);c=q(g,c);this.c.beginPath();this.strokeStyle(g,h).moveTo(a,b).lineTo(d,c).c.stroke();this.c.closePath();this.c.restore();return this},round:function(a,b,d,c,g,h){this.c.beginPath();this.c.fillStyle=c;this.c.arc(a,b,d,0,x,!1);this.c.closePath();this.c.fill();g&&(this.c.lineWidth=g,this.c.strokeStyle=h||"#010101",this.c.stroke());return this},backgound:function(a,b,d,
c,g){this.c.save();this.c.globalCompositeOperation="destination-over";this.c.translate(a,b);this.c.beginPath();this.c.fillStyle=g;this.c.fillRect(0,0,d,c);this.c.restore();return this},rectangle:function(a,b,d,c,g,h,e,f,o,j,m,k,n){this.c.save();a=q(e,a);b=q(e,b);this.c.translate(a,b);this.c.beginPath();this.c.fillStyle=g;this.shadowOn(o,j,m,k,n);h&&i.isNumber(e)&&(this.c.lineWidth=e,this.c.strokeStyle=f,this.c.strokeRect(0,0,d,c));this.c.fillRect(0,0,d,c);h&&i.isArray(e)&&(this.c.strokeStyle=f,this.line(0,
0,d,0,e[0],f),this.line(d,0,d,c,e[1],f),this.line(0,c,d,c,e[2],f),this.line(0,0,0,c,e[3],f));this.c.restore();return this},clearRect:function(a,b,d,c){d=d||this.width;c=c||this.height;this.c.clearRect(a||0,b||0,d,c);return this},drawBorder:function(a,b,d,c,g,h,e,f,o,j,m,k,n,l){this.c.save();var p=q(g,a),r=q(g,b);p!=a&&(a=p,d-=1);r!=b&&(b=r,c-=1);this.c.translate(a,b);this.c.lineWidth=g;this.c.strokeStyle=h;o&&(this.c.globalCompositeOperation="destination-over");f&&(this.c.fillStyle=f);e=0==e?0:i.parseBorder(e);
i.isArray(e)?(this.c.beginPath(),this.c.moveTo(e[0],0),this.c.lineTo(d-e[1],0),this.c.arcTo(d,0,d,e[1],e[1]),this.c.lineTo(d,c-e[2]),this.c.arcTo(d,c,d-e[2],c,e[2]),this.c.lineTo(e[3],c),this.c.arcTo(0,c,0,c-e[3],e[3]),this.c.lineTo(0,e[0]),this.c.arcTo(0,0,e[0],0,e[0]),this.c.closePath(),this.shadowOn(j,m,k,n,l),f&&this.c.fill(),j&&this.shadowOff(),this.c.globalCompositeOperation="source-over",this.c.stroke()):(this.shadowOn(j,m,k,n,l),f&&this.c.fillRect(0,0,d,c),j&&this.shadowOff(),this.c.strokeRect(0,
0,d,c));this.c.restore();return this},toImageURL:function(){return this.canvas.toDataURL("image/png")},addEvent:function(a,b,d){i.Event.addEvent(this.canvas,a,b,d)}};i.Chart=i.extend(i.Painter,{configure:function(){i.Chart.superclass.configure.apply(this,arguments);this.type="chart";this.set({render:"",data:[],width:void 0,height:void 0,align:"center",segmentRect:!0,title:"",title_align:"center",title_valign:"top",title_writingmode:"lr",title_font:"Verdana",title_fontweight:"bold",title_fontsize:20,
title_color:"black",title_height:25,animation:!1,doAnimationFn:i.emptyFn,animation_timing_function:"easeInOut",duration_animation_duration:1600,legend:{enable:!1},tip:{enable:!1}});this.registerEvent("parseData","parseTipText","parseLabelText","beforeAnimation","afterAnimation");this.T=null;this.animationed=this.rendered=!1;this.components=[];this.total=0},pushComponent:function(a,b){i.isArray(a)?this.components=b?a.concat(this.components):this.components.concat(a):b?this.components=[a].concat(this.components):
this.components.push(a)},plugin:function(a,b){this.init();a.inject(this);this.pushComponent(a,b)},toImageURL:function(){return this.T.toImageURL()},segmentRect:function(){this.T.clearRect(this.get("l_originx"),this.get("t_originy"),this.get("client_width"),this.get("client_height"))},resetCanvas:function(){this.T.backgound(this.get("l_originx"),this.get("t_originy"),this.get("client_width"),this.get("client_height"),this.get("background_color"))},animation:function(){return function(a){a.segmentRect();
a.doAnimation(a.variable.animation.time,a.duration);a.resetCanvas();a.variable.animation.time<a.duration?(a.variable.animation.time++,setTimeout(function(){a.animation(a)},i.INTERVAL)):setTimeout(function(){a.variable.animation.time=0;a.animationed=!0;a.draw();a.processAnimation=!1;a.fireEvent(this,"afterAnimation",[this])},i.INTERVAL)}}(),doAnimation:function(a,b){this.get("doAnimationFn").call(this,a,b)},commonDraw:function(){i.Assert.isTrue(this.rendered,this.type+" has not rendered.");i.Assert.isTrue(this.initialization,
this.type+" has initialize failed.");i.Assert.gtZero(this.data.length,this.type+"'data is empty.");this.redraw||(this.title(),this.get("border.enable")?this.T.drawBorder(0,0,this.width,this.height,this.get("border.width"),this.get("border.color"),this.get("border.radius"),this.get("background_color"),!0):this.T.backgound(0,0,this.width,this.height,this.get("background_color")));this.redraw=!0;if(!this.animationed&&this.get("animation"))this.fireEvent(this,"beforeAnimation",[this]),this.animation(this);
else{this.segmentRect();for(var a=0;a<this.components.length;a++)this.components[a].draw();this.resetCanvas()}},title:function(){""!=this.get("title")&&("tb"!=this.get("title_writingmode")&&("left"==this.get("title_align")?this.push("title_originx",this.get("padding_left")):"right"==this.get("title_align")?this.push("title_originx",this.width-this.get("padding_right")):this.push("title_originx",this.get("client_width")/2),this.T.textAlign(this.get("title_align")),"bottom"==this.get("title_valign")?
this.push("title_originy",this.height-this.get("padding_bottom")):this.push("title_originy",this.get("padding_top")),this.T.textBaseline(this.get("title_valign"))),this.T.textFont(i.getFont(this.get("title_fontweight"),this.get("title_fontsize"),this.get("title_font"))),this.T.fillText(this.get("title"),this.get("title_originx"),this.get("title_originy"),this.get("client_width"),this.get("title_color")))},create:function(a){this.width=this.push("width",this.get("width")||400);this.height=this.push("height",
this.get("height")||300);var b="width:"+this.width+"px;height:"+this.height+"px;padding:0px;overflow:hidden;position:relative;",d=i.iGather(this.type);this.shellid=i.iGather(this.type+"-shell");a.innerHTML="<div id='"+this.shellid+"' style='"+b+"'><canvas id= '"+d+"'  width='"+this.width+"' height="+this.height+"'><p>Your browser does not support the canvas element</p></canvas></div>";this.element=document.getElementById(d);this.shell=document.getElementById(this.shellid);this.T=this.target=new w(this.element);
this.rendered=!0},render:function(a){this.push("render",a)},initialize:function(){if(!this.rendered){var a=this.get("render");"string"==typeof a&&document.getElementById(a)?this.create(document.getElementById(a)):"object"==typeof a&&this.create(a)}0<this.get("data").length&&this.rendered&&!this.initialization&&(i.Interface.parser.call(this),this.doConfig(),this.initialization=!0)},doConfig:function(){i.Chart.superclass.doConfig.call(this);var a=this,b=a.variable.event;a.get("animation")&&(a.processAnimation=
a.get("animation"),a.duration=Math.ceil(a.get("duration_animation_duration")*i.FRAME/1E3),a.variable.animation={time:0},a.animationArithmetic=i.getAnimationArithmetic(a.get("animation_timing_function")));a.is3D()&&i.Interface._3D.call(a);a.T.strokeStyle(a.get("brushsize"),a.get("strokeStyle"),a.get("lineJoin"));a.T.addEvent("click",function(b){a.fireEvent(a,"click",[i.Event.fix(b)])},!1);a.T.addEvent("mousemove",function(b){a.fireEvent(a,"mousemove",[i.Event.fix(b)])},!1);a.on("click",function(b){if(!a.processAnimation)for(var c,
e=0;e<a.components.length;e++){c=a.components[e];if(!c.preventEvent){var d=c.isMouseOver(b);d.valid&&a.components[e].fireEvent(c,"click",[b,d])}}});a.on("mousemove",function(c){if(!a.processAnimation){for(var d=false,e=0;e<a.components.length;e++){var f=a.components[e],i=f.variable.event;if(!f.preventEvent){var j=f.isMouseOver(c);if(j.valid){d=true;if(!b.mouseover){b.mouseover=true;a.T.css("cursor","pointer");a.fireEvent(a,"mouseover",[c])}if(!i.mouseover){i.mouseover=true;f.fireEvent(f,"mouseover",
[c,j])}f.fireEvent(f,"mousemove",[c,j])}else if(i.mouseover){i.mouseover=false;f.fireEvent(f,"mouseout",[c,j])}}}if(!d&&b.mouseover){b.mouseover=false;a.T.css("cursor","default");a.fireEvent(a,"mouseout",[c])}}});i.Assert.isArray(a.data);a.push("l_originx",a.get("padding_left"));a.push("r_originx",a.width-a.get("padding_right"));a.push("t_originy",a.get("padding_top"));a.push("b_originy",a.height-a.get("padding_bottom"));var d=0,c=0;""!=a.get("title")&&("tb"==a.get("title_writingmode")?(d=a.get("title_height"),
"left"==a.get("title_align")?a.push("l_originx",a.get("l_originx")+a.get("title_height")):a.push("r_originx",a.width-a.get("l_originx")-a.get("title_height"))):(c=a.get("title_height"),"left"==a.get("title_align")?a.push("title_originx",a.get("padding_left")):"right"==a.get("title_align")?a.push("title_originx",a.width-a.get("padding_right")):a.push("title_originx",a.get("client_width")/2),"bottom"==a.get("title_valign")?(a.push("title_originy",a.height-a.get("padding_bottom")),a.push("b_originy",
a.height-a.get("b_originy")-a.get("title_height"))):(a.push("t_originy",a.get("t_originy")+a.get("title_height")),a.push("title_originy",a.get("padding_top")))));a.push("client_width",a.get("width")-a.get("hpadding")-d);a.push("client_height",a.get("height")-a.get("vpadding")-c);a.push("minDistance",Math.min(a.get("client_width"),a.get("client_height")));a.push("maxDistance",Math.max(a.get("client_width"),a.get("client_height")));a.push("minstr",a.get("client_width")<a.get("client_height")?"width":
"height");a.push("centerx",a.get("l_originx")+a.get("client_width")/2);a.push("centery",a.get("t_originy")+a.get("client_height")/2);a.get("legend.enable")&&(a.legend=new i.Legend(i.apply({maxwidth:a.get("client_width"),data:a.data},a.get("legend")),a),a.components.push(a.legend));a.get("tip.enable")&&a.push("tip.wrap",a.shell)}})})(iChart);
