iChart.KeDu=iChart.extend(iChart.Component,{configure:function(){iChart.KeDu.superclass.configure.apply(this,arguments);this.type="kedu";this.set({which:"h",distance:void 0,start_scale:0,end_scale:void 0,min_scale:void 0,max_scale:void 0,scale:void 0,scale_share:5,scale_line_enable:!0,scale_size:1,scale_width:4,scale_color:"#333333",scaleAlign:"center",labels:[],kedu2grid:!0,text_height:16,text_space:4,textAlign:"left",decimalsnum:0,join_style:"none",join_size:2,label:"",label_position:""});this.registerEvent("parseText");
this.items=[];this.number=0},isEventValid:function(){return{valid:!1}},doDraw:function(){var d=y=x0=y0=tx=ty=0,a=this.get("scale_width"),c=this.get("scale_width")/2;this.isHorizontal?("top"==this.get("scaleAlign")?y=-a:"center"==this.get("scaleAlign")?(y=-c,y0=c):y0=a,this.T.textAlign("center"),"top"==this.get("textAlign"))?(ty=-this.get("text_space"),this.T.textBaseline("bottom")):(ty=this.get("text_space"),this.T.textBaseline("top")):("left"==this.get("scaleAlign")?d=-a:"center"==
this.get("scaleAlign")?(d=-c,x0=c):x0=a,this.T.textBaseline("middle"),"right"==this.get("textAlign"))?(this.T.textAlign("left"),tx=this.get("text_space")):(this.T.textAlign("right"),tx=-this.get("text_space"));this.T.textFont(this.get("fontStyle"));for(a=0;a<this.items.length;a++)this.get("scale_line_enable")&&this.T.line(this.items[a].x+d,this.items[a].y+y,this.items[a].x+x0,this.items[a].y+y0,this.get("scale_size"),this.get("scale_color"),!1),this.T.fillText(this.items[a].text,
this.items[a].textX+tx,this.items[a].textY+ty,!1,this.get("color"),"lr",this.get("text_height"))},doConfig:function(){iChart.KeDu.superclass.doConfig.call(this);iChart.Assert.isNumber(this.get("distance"),"distance");var d=0<this.get("labels").length;d?this.number=this.get("labels").length-1:(iChart.Assert.isTrue(iChart.isNumber(this.get("max_scale"))||iChart.isNumber(this.get("end_scale")),"max_scale&end_scale"),(!this.get("end_scale")||this.get("end_scale")<this.get("max_scale"))&&this.push("end_scale",
iChart.ceil(this.get("max_scale"))),this.get("start_scale")>this.get("min_scale")&&this.push("start_scale",iChart.floor(this.get("min_scale"))),this.get("scale")&&this.get("scale")<this.get("end_scale")-this.get("start_scale")&&this.push("scale_share",(this.get("end_scale")-this.get("start_scale"))/this.get("scale")),(!this.get("scale")||this.get("scale")>this.get("end_scale")-this.get("start_scale"))&&this.push("scale",(this.get("end_scale")-this.get("start_scale"))/this.get("scale_share")),this.number=
this.get("scale_share"));this.push("distanceOne",this.get("valid_distance")/this.number);var a,c=0,e,b;this.T.textFont(this.get("fontStyle"));this.push("which",this.get("which").toLowerCase());this.isHorizontal="h"==this.get("which");for(var f=0;f<=this.number;f++)a=d?this.get("labels")[f]:(this.get("scale")*f+this.get("start_scale")).toFixed(this.get("decimalsnum")),e=this.isHorizontal?this.get("valid_x")+f*this.get("distanceOne"):this.x,b=this.isHorizontal?this.y:this.get("valid_y")+this.get("distance")-
f*this.get("distanceOne"),this.items.push(iChart.merge({text:a,x:e,y:b,textX:e,textY:b},this.fireEvent(this,"parseText",[a,e,b,f]))),c=Math.max(c,this.T.measureText(a));this.left=this.right=this.top=this.bottom=0;this.isHorizontal?(this.top="top"==this.get("scaleAlign")?this.get("scale_width"):"center"==this.get("scaleAlign")?this.get("scale_width")/2:0,this.bottom=this.get("scale_width")-this.top,"top"==this.get("textAlign")?this.top+=this.get("text_height")+this.get("text_space"):this.bottom+=
this.get("text_height")+this.get("text_space")):(this.left="left"==this.get("scaleAlign")?this.get("scale_width"):"center"==this.get("scaleAlign")?this.get("scale_width")/2:0,this.right=this.get("scale_width")-this.left,"left"==this.get("textAlign")?this.left+=c+this.get("text_space"):this.right+=c+this.get("text_space"))}});
iChart.Coordinate2D=iChart.extend(iChart.Component,{configure:function(){iChart.Coordinate2D.superclass.configure.apply(this,arguments);this.type="coordinate2d";this.set({sign_size:12,sign_space:5,kedu:[],valid_width:void 0,valid_height:void 0,grid_line_width:1,grid_color:"#c4dede",gridlinesVisible:!0,kedu2grid:!0,grids:void 0,ignoreOverlap:!0,ignoreEdge:!1,gradient:!1,ylabel:"",xlabel:"",decimalsnum:0,color_factor:0.18,background_color:"#FEFEFE",alternate_color:!0,crosshair:{enable:!1},width:void 0,
height:void 0,axis:{enable:!0,color:"#666666",width:1,style:""}});this.registerEvent();this.kedu=[];this.gridlines=[]},getScale:function(d){for(var a=0;a<this.kedu.length;a++)if(this.kedu[a].get("position")==d)return{start:this.kedu[a].get("start_scale"),end:this.kedu[a].get("end_scale"),distance:this.kedu[a].get("end_scale")-this.kedu[a].get("start_scale")};return{start:0,end:0,distance:0}},isEventValid:function(d){return{valid:d.offsetX>this.x&&d.offsetX<this.x+this.get("width")&&d.offsetY<this.y+
this.get("height")&&d.offsetY>this.y}},doDraw:function(){this.T.rectangle(this.x,this.y,this.get("width"),this.get("height"),this.get("fill_color"),this.get("axis.enable"),this.get("axis.width"),this.get("axis.color"),this.get("shadow"),this.get("shadow_color"),this.get("shadow_blur"),this.get("shadow_offsetx"),this.get("shadow_offsety"));if(this.get("alternate_color")){var d,a=!1,c=[0,0,0,0],e=iChart.dark(this.get("background_color"),0.04);this.get("axis.enable")&&(c=this.get("axis.width"))}for(var b=
0;b<this.gridlines.length;b++)this.gridlines[b].x1=Math.round(this.gridlines[b].x1),this.gridlines[b].y1=Math.round(this.gridlines[b].y1),this.gridlines[b].x2=Math.round(this.gridlines[b].x2),this.gridlines[b].y2=Math.round(this.gridlines[b].y2),this.get("alternate_color")&&this.gridlines[b].y1==this.gridlines[b].y2&&(a&&this.T.rectangle(this.gridlines[b].x1+c[3],this.gridlines[b].y1+this.get("grid_line_width"),this.gridlines[b].x2-this.gridlines[b].x1-c[3]-c[1],d-this.gridlines[b].y1-this.get("grid_line_width"),
e),d=this.gridlines[b].y1,a=!a),this.T.line(this.gridlines[b].x1,this.gridlines[b].y1,this.gridlines[b].x2,this.gridlines[b].y2,this.get("grid_line_width"),this.get("grid_color"));for(b=0;b<this.kedu.length;b++)this.kedu[b].draw()},doConfig:function(){iChart.Coordinate2D.superclass.doConfig.call(this);iChart.Assert.isNumber(this.get("width"),"width");iChart.Assert.isNumber(this.get("height"),"height");this.on("mouseover",function(){this.T.css("cursor","default")});(!this.get("valid_width")||
this.get("valid_width")>this.get("width"))&&this.push("valid_width",this.get("width"));(!this.get("valid_height")||this.get("valid_height")>this.get("height"))&&this.push("valid_height",this.get("height"));this.get("gradient")&&iChart.isString(this.get("background_color"))&&this.push("fill_color",this.T.avgLinearGradient(this.x,this.y,this.x,this.y+this.get("height"),[this.get("dark_color"),this.get("light_color")]));if(this.get("axis.enable")){var d=this.get("axis.width");iChart.isArray(d)||
this.push("axis.width",[d,d,d,d])}this.get("crosshair.enable")&&(this.push("crosshair.wrap",this.container.shell),this.push("crosshair.height",this.get("height")),this.push("crosshair.width",this.get("width")),this.push("crosshair.top",this.y),this.push("crosshair.left",this.x),this.crosshair=new iChart.CrossHair(this.get("crosshair"),this));var a,c,e=!(!this.get("gridlinesVisible")||!this.get("grids")),d=e&&!!this.get("grids.horizontal"),b=e&&!!this.get("grids.vertical"),f=this.get("height"),i=this.get("width"),
g=this.get("valid_width"),h=this.get("valid_height"),k=this.get("gridlinesVisible")&&this.get("kedu2grid")&&!(d&&b),l=(i-g)/2;sh=(f-h)/2;axis=this.get("axis.width");iChart.isArray(this.get("kedu"))||(iChart.isObject(this.get("kedu"))?this.push("kedu",[this.get("kedu")]):this.push("kedu",[]));for(e=0;e<this.get("kedu").length;e++)a=this.get("kedu")[e],c=(c=a.position)||"left",c=c.toLowerCase(),a.originx=this.x,a.originy=this.y,a.valid_x=this.x+l,a.valid_y=this.y+sh,a.position=c,"top"==c?(a.which="h",
a.distance=i,a.valid_distance=g):"right"==c?(a.which="v",a.distance=f,a.valid_distance=h,a.originx+=i,a.valid_x+=g):"bottom"==c?(a.which="h",a.distance=i,a.valid_distance=g,a.originy+=f,a.valid_y+=h):(a.which="v",a.distance=f,a.valid_distance=h),this.kedu.push(new iChart.KeDu(a,this.container));this.push("ignoreOverlap",this.get("ignoreOverlap")&&this.get("axis.enable")||this.get("ignoreEdge"));if(this.get("ignoreOverlap"))var j=this.get("ignoreEdge")?function(a,b,c){return a=="v"?c==this.y||c==this.y+
f:b==this.x||b==this.x+a}:function(a,b,c){return a=="v"?c==this.y&&axis[0]>0||c==this.y+f&&axis[2]>0:b==this.x&&axis[3]>0||b==this.x+i&&axis[1]>0};if(k)for(e=0;e<this.kedu.length;e++)if(a=this.kedu[e],!iChart.isFalse(a.get("kedu2grid"))&&!(d&&"v"==a.get("which")||b&&"h"==a.get("which"))){c=g=0;"top"==a.get("position")?g=f:"right"==a.get("position")?c=-i:"bottom"==a.get("position")?g=-f:c=i;for(h=0;h<a.items.length;h++)(!this.get("ignoreOverlap")||!j.call(this,a.get("which"),a.items[h].x,a.items[h].y))&&
this.gridlines.push({x1:a.items[h].x,y1:a.items[h].y,x2:a.items[h].x+c,y2:a.items[h].y+g})}if(b){e=this.get("grids.vertical");iChart.Assert.gtZero(e.value,"value");b=i/e.value;a=e.value;"given_value"==e.way&&(a=b,b=e.value,b=b>i?i:b);for(e=0;e<=a;e++)(!this.get("ignoreOverlap")||!j.call(this,"h",this.x+e*b,this.y))&&this.gridlines.push({x1:this.x+e*b,y1:this.y,x2:this.x+e*b,y2:this.y+f})}if(d){d=this.get("grids.horizontal");iChart.Assert.gtZero(d.value,"value");b=f/d.value;a=d.value;"given_value"==
d.way&&(a=b,b=d.value,b=b>f?f:b);for(e=0;e<=a;e++)(!this.get("ignoreOverlap")||!j.call(this,"v",this.x,this.y+e*b))&&this.gridlines.push({x1:this.x,y1:this.y+e*b,x2:this.x+i,y2:this.y+e*b})}}});
iChart.Coordinate3D=iChart.extend(iChart.Coordinate2D,{configure:function(){iChart.Coordinate3D.superclass.configure.apply(this,arguments);this.type="coordinate3d";this.dimension=iChart._3D;this.set({xAngle:60,yAngle:20,xAngle_:void 0,yAngle_:void 0,zHeight:0,pedestal_height:22,board_deep:20,gradient:!0,ignoreEdge:!0,alternate_color:!1,shadow:!0,grid_color:"#7a8d44",background_color:"#d6dbd2",shadow_offsetx:4,shadow_offsety:2,wall_style:[],axis:{enable:!1}})},doDraw:function(){this.T.cube3D(this.x,
this.y+this.get("height")+this.get("pedestal_height"),this.get("xAngle_"),this.get("yAngle_"),!1,this.get("width"),this.get("pedestal_height"),3*this.get("zHeight")/2,this.get("axis.enable"),this.get("axis.width"),this.get("axis.color"),this.get("bottom_style"));this.T.cube3D(this.x+this.get("board_deep")*this.get("xAngle_"),this.y+this.get("height")-this.get("board_deep")*this.get("yAngle_"),this.get("xAngle_"),this.get("yAngle_"),!1,this.get("width"),this.get("height"),this.get("zHeight"),
this.get("axis.enable"),this.get("axis.width"),this.get("axis.color"),this.get("board_style"));this.T.cube3D(this.x,this.y+this.get("height"),this.get("xAngle_"),this.get("yAngle_"),!1,this.get("width"),this.get("height"),this.get("zHeight"),this.get("axis.enable"),this.get("axis.width"),this.get("axis.color"),this.get("wall_style"));for(var d=this.get("xAngle_")*this.get("zHeight"),a=this.get("yAngle_")*this.get("zHeight"),c=0;c<this.gridlines.length;c++)this.T.line(this.gridlines[c].x1,
this.gridlines[c].y1,this.gridlines[c].x1+d,this.gridlines[c].y1-a,this.get("grid_line_width"),this.get("grid_color")),this.T.line(this.gridlines[c].x1+d,this.gridlines[c].y1-a,this.gridlines[c].x2+d,this.gridlines[c].y2-a,this.get("grid_line_width"),this.get("grid_color"));for(c=0;c<this.kedu.length;c++)this.kedu[c].draw()},doConfig:function(){iChart.Coordinate3D.superclass.doConfig.call(this);var d=this.get("background_color"),a=iChart.dark(d,0.1),c=this.get("height"),e=this.get("width");3>
this.get("wall_style").length&&this.push("wall_style",[{color:a},{color:d},{color:a}]);var b=this.get("wall_style")[0].color;this.push("bottom_style",[{color:d,shadow:this.get("shadow"),shadowColor:this.get("shadow_color"),blur:this.get("shadow_blur"),sx:this.get("shadow_offsetx"),sy:this.get("shadow_offsety")},!1,!1,{color:b},{color:b},{color:b}]);this.push("board_style",[!1,!1,!1,{color:b},{color:d},!1]);if(this.get("gradient")){var f=this.get("xAngle_")*this.get("zHeight"),i=this.get("yAngle_")*
this.get("zHeight"),g=this.get("wall_style"),h=this.get("bottom_style");iChart.isString(g[0].color)&&(g[0].color=this.T.avgLinearGradient(this.x,this.y+c,this.x+e,this.y+c,[b,this.get("dark_color")]));iChart.isString(g[1].color)&&(g[1].color=this.T.avgLinearGradient(this.x+f,this.y-i,this.x+f,this.y+c-i,[this.get("dark_color"),this.get("light_color")]));iChart.isString(g[2].color)&&(g[2].color=this.T.avgLinearGradient(this.x,this.y,this.x,this.y+c,[d,this.get("dark_color")]));h[5].color=
this.T.avgLinearGradient(this.x,this.y+c,this.x,this.y+c+this.get("pedestal_height"),[d,a])}}});
