(function(h){function w(a){"string"===typeof a&&(a=document.getElementById(a));if(!a||!a.tagName||"canvas"!=a.tagName.toLowerCase())throw Error("there not a canvas element;can't use it");this.canvas=a;this.ctx=this.canvas.getContext("2d");this.width=this.canvas.width;this.height=this.canvas.height}var v=Math.PI/90,l=Math.PI,x=2*Math.PI,r=Math.sin,s=Math.cos;w.prototype={css:function(a,b){if(h.isDefined(b))this.canvas.style[a]=b;else return this.canvas.style[a]},arc:function(a,b,c,e,f,i,d,g,h,j,m,
k,n,t,p,q,l){p=!!p;q=!!q;this.ctx.save();this.fillStyle(i);l&&(this.ctx.globalCompositeOperation="destination-over");d&&this.strokeStyle(g,h);this.shadowOn(j,m,k,n,t);this.ctx.moveTo(a,b);this.ctx.beginPath();this.ctx.arc(a,b,c,e,f,p);q&&this.ctx.lineTo(a,b);this.ctx.closePath();this.ctx.fill();d&&this.ctx.stroke();this.ctx.restore();return this},ellipse:function(a,b,c,e,f,i,d,g,h,j,m,k,n,t,p,q,l,y){q=!!q;l=!!l;this.ctx.save();y&&(this.ctx.globalCompositeOperation="destination-over");e&&this.strokeStyle(h,
j);this.shadowOn(m,k,n,t,p);this.ctx.moveTo(a,b);this.ctx.beginPath();l&&this.ctx.moveTo(a,b);for(this.fillStyle(d);f<=i;)this.ctx.lineTo(a+c*s(f),b+(q?-e*r(f):e*r(f))),f+=v;this.ctx.lineTo(a+c*s(i),b+(q?-e*r(i):e*r(i)));this.ctx.closePath();e&&this.ctx.stroke();this.ctx.fill();this.ctx.restore();return this},sector:function(a,b,c,e,f,i,d,g,h,j,m,k,n,t,p){j?(this.arc(a,b,c,e,f,i,d,g,h,j,m,k,n,t,p,!0),this.arc(a,b,c,e,f,i,d,g,h,!1,m,k,n,t,p,!0)):this.arc(a,b,c,e,f,i,d,g,h,!1,0,0,0,0,p,!0);return this},
sector3D:function(){var a=function(a,b,f,i,d,g,o,j,m){if(o&&g<=l||!o&&d>=l)return!1;var k=function(d,g){this.ctx.lineTo(a+f*s(d),b+(g||0)+(o?-i*r(d):i*r(d)))},d=o&&g>l&&d<l?l:d,g=!o&&d<l&&g>l?l:g,n=d;this.ctx.fillStyle=h.Math.dark(m);this.ctx.moveTo(a+f*s(d),b+(o?-i*r(d):i*r(d)));for(this.ctx.beginPath();n<=g;)k.call(this,n),n+=v;k.call(this,g);this.ctx.lineTo(a+f*s(g),b+j+(o?-i*r(g):i*r(g)));for(n=g;n>=d;)k.call(this,n,j),n-=v;k.call(this,d,j);this.ctx.lineTo(a+f*s(d),b+(o?-i*r(d):i*r(d)));this.ctx.closePath();
this.ctx.fill()},b=function(a,b,f,i,d,g,o,j){this.ctx.moveTo(a,b);this.ctx.beginPath();this.ctx.fillStyle=h.Math.dark(j);this.ctx.lineTo(a,b+g);f=a+f*s(o);i=b+g+(d?-i*r(o):i*r(o));this.ctx.lineTo(f,i);this.ctx.lineTo(f,i-g);this.ctx.lineTo(a,b);this.ctx.closePath();this.ctx.fill()};return function(c,e,f,i,d,g,o,j,m,k,n,t,p,q,r,s,u){t=t&&!h.isOpera;this.ctx.save();this.ctx.globalCompositeOperation="destination-over";this.ctx.fillStyle=j;var v=u?d<l/2||d>1.5*l:d>l/2&&d<1.5*l,w=u?g>l/2&&g<1.5*l:g<l/
2||g>1.5*l;if(v||w)v&&b.call(this,c,e,f,i,u,o,d,j),w&&b.call(this,c,e,f,i,u,o,g,j);this.ellipse(c,e+o,f,i,d,g,j,m,k,n,t,p,q,r,s,u,!0);this.ctx.globalCompositeOperation="source-over";this.ellipse(c,e,f,i,d,g,j,m,k,n,!1,p,q,r,s,u,!0);a.call(this,c,e,f,i,d,g,u,o,j);this.ctx.restore();return this}}(),textStyle:function(a,b,c){return this.textAlign(a).textBaseline(b).textFont(c)},strokeStyle:function(a,b,c){a&&(this.ctx.lineWidth=a);b&&(this.ctx.strokeStyle=b);c&&(this.ctx.lineJoin=c);return this},globalAlpha:function(a){a&&
(this.ctx.globalAlpha=a);return this},fillStyle:function(a){a&&(this.ctx.fillStyle=a);return this},textAlign:function(a){a&&(this.ctx.textAlign=a);return this},textBaseline:function(a){a&&(this.ctx.textBaseline=a);return this},textFont:function(a){a&&(this.ctx.font=a);return this},shadowOn:function(a,b,c,e,f){h.isString(a)&&(f=e,e=c,c=b,b=!0);a&&(this.ctx.shadowColor=b,this.ctx.shadowBlur=c,this.ctx.shadowOffsetX=e,this.ctx.shadowOffsetY=f);return this},shadowOff:function(){this.ctx.shadowColor="white";
this.ctx.shadowBlur=this.ctx.shadowOffsetX=this.ctx.shadowOffsetY=0},avgLinearGradient:function(a,b,c,e,f){a=this.createLinearGradient(a,b,c,e);for(b=0;b<f.length;b++)a.addColorStop(b/(f.length-1),f[b]);return a},createLinearGradient:function(a,b,c,e){return this.ctx.createLinearGradient(a,b,c,e)},avgRadialGradient:function(a,b,c,e,f,i,d){a=this.createRadialGradient(a,b,c,e,f,i);for(b=0;b<d.length;b++)a.addColorStop(b/(d.length-1),d[b]);return a},createRadialGradient:function(a,b,c,e,f,i){return this.ctx.createRadialGradient(a,
b,c,e,f,i)},fillText:function(a,b,c,e,f,i,d){a+="";e=e||!1;i=i||"lr";d=d||16;this.fillStyle(f);a=a.split("tb"==i?"":"\n");for(f=0;f<a.length;f++)e?this.ctx.fillText(a[f],b,c,e):this.ctx.fillText(a[f],b,c),c+=d;return this},measureText:function(a){return this.ctx.measureText(a).width},moveTo:function(a,b){this.ctx.moveTo(a||0,b||0);return this},lineTo:function(a,b){this.ctx.lineTo(a||0,b||0);return this},save:function(){this.ctx.save();return this},restore:function(){this.ctx.restore();return this},
beginPath:function(){this.ctx.beginPath();return this},closePath:function(){this.ctx.closePath();return this},stroke:function(){this.ctx.stroke();return this},fill:function(){this.ctx.fill();return this},text:function(a,b,c,e,f,i,d,g,h,j){this.ctx.save();this.textStyle(i,d,g);this.fillText(a,b,c,e,f,h,j);this.ctx.restore();return this},cube:function(a,b,c,e,f,i,d,g,o,j,m,k,n,l,p,q){a=h.Math.fixDeckle(j,a);b=h.Math.fixDeckle(j,b);d=d&&0<d?d:f;e=b-d*e;c=h.Math.fixDeckle(j,a+d*c);e=h.Math.fixDeckle(j,
e);k&&(this.polygon(g,o,j,m,k,n,l,p,q,!1,[a,b,c,e,c+f,e,a+f,b]),this.polygon(g,o,j,m,k,n,l,p,q,!1,[a,b,a,b+i,a+f,b+i,a+f,b]),this.polygon(g,o,j,m,k,n,l,p,q,!1,[a+f,b,c+f,e,c+f,e+i,a+f,b+i]));this.polygon(h.Math.dark(g),o,j,m,!1,n,l,p,q,!1,[a,b,c,e,c+f,e,a+f,b]);this.polygon(g,o,j,m,!1,n,l,p,q,!1,[a,b,a,b+i,a+f,b+i,a+f,b]);this.polygon(h.Math.dark(g),o,j,m,!1,n,l,p,q,!1,[a+f,b,c+f,e,c+f,e+i,a+f,b+i]);return this},cube3D:function(a,b,c,e,f,i,d,g,o,j,m,k){a=h.Math.fixDeckle(j,a);b=h.Math.fixDeckle(j,
b);if(!g||0==g)g=i;f?(e=h.Math.vectorP2P(c,e),c=a+g*e.x,e=b-g*e.y):(c=a+g*c,e=b-g*e);for(;6>k.length;)k.push(!1);c=h.Math.fixDeckle(j,c);e=h.Math.fixDeckle(j,e);g=[];0>e?h.isObject(k[4])&&g.push(h.applyIf({points:[a,b-d,c,e-d,c+i,e-d,a+i,b-d]},k[4])):h.isObject(k[0])&&g.push(h.applyIf({points:[a,b,c,e,c+i,e,a+i,b]},k[0]));h.isObject(k[1])&&g.push(h.applyIf({points:[c,e,c,e-d,c+i,e-d,c+i,e]},k[1]));h.isObject(k[2])&&g.push(h.applyIf({points:[a,b,a,b-d,c,e-d,c,e]},k[2]));h.isObject(k[3])&&g.push(h.applyIf({points:[a+
i,b,a+i,b-d,c+i,e-d,c+i,e]},k[3]));0>e?h.isObject(k[0])&&g.push(h.applyIf({points:[a,b,c,e,c+i,e,a+i,b]},k[0])):h.isObject(k[4])&&g.push(h.applyIf({points:[a,b-d,c,e-d,c+i,e-d,a+i,b-d]},k[4]));h.isObject(k[5])&&g.push(h.applyIf({points:[a,b,a,b-d,a+i,b-d,a+i,b]},k[5]));for(a=0;a<g.length;a++)this.polygon(g[a].color,o,j,m,g[a].shadow,g[a].shadowColor,g[a].blur,g[a].sx,g[a].sy,g[a].alpha,g[a].points);return this},polygon:function(a,b,c,e,f,i,d,g,h,j,m){if(!(2>m.length)){this.ctx.save();this.strokeStyle(c,
e);this.ctx.beginPath();this.fillStyle(a).globalAlpha(j).shadowOn(f,i,d,g,h).moveTo(m[0],m[1]);for(a=2;a<m.length;a+=2)this.lineTo(m[a],m[a+1]);this.ctx.closePath();b&&this.ctx.stroke();this.ctx.fill();this.ctx.restore();return this}},line:function(a,b,c,e,f,i,d){if(!f||0==f)return this;this.ctx.save();d&&(this.ctx.globalCompositeOperation="destination-over");a=h.Math.fixDeckle(f,a);b=h.Math.fixDeckle(f,b);c=h.Math.fixDeckle(f,c);e=h.Math.fixDeckle(f,e);this.ctx.beginPath();this.strokeStyle(f,i).moveTo(a,
b).lineTo(c,e).ctx.stroke();this.ctx.closePath();this.ctx.restore();return this},round:function(a,b,c,e,f,i){this.ctx.beginPath();this.ctx.fillStyle=e;this.ctx.arc(a,b,c,0,x,!1);this.ctx.closePath();this.ctx.fill();f&&(this.ctx.lineWidth=f,this.ctx.strokeStyle=i||"#010101",this.ctx.stroke());return this},backgound:function(a,b,c,e,f){this.ctx.save();this.ctx.globalCompositeOperation="destination-over";this.ctx.translate(a,b);this.ctx.beginPath();this.ctx.fillStyle=f;this.ctx.fillRect(0,0,c,e);this.ctx.restore();
return this},rectangle:function(a,b,c,e,f,i,d,g,o,j,m,k,n){this.ctx.save();a=h.Math.fixDeckle(d,a);b=h.Math.fixDeckle(d,b);this.ctx.translate(a,b);this.ctx.beginPath();this.ctx.fillStyle=f;this.shadowOn(o,j,m,k,n);i&&h.isNumber(d)&&(this.ctx.lineWidth=d,this.ctx.strokeStyle=g,this.ctx.strokeRect(0,0,c,e));this.ctx.fillRect(0,0,c,e);i&&h.isArray(d)&&(this.ctx.strokeStyle=g,this.line(0,0,c,0,d[0],g),this.line(c,0,c,e,d[1],g),this.line(0,e,c,e,d[2],g),this.line(0,0,0,e,d[3],g));this.ctx.restore();return this},
clearRect:function(a,b,c,e){c=c||this.width;e=e||this.height;this.ctx.clearRect(a||0,b||0,c,e);return this},drawBorder:function(a,b,c,e,f,i,d,g,o,j,m,k,n,l){this.ctx.save();var p=h.Math.fixDeckle(f,a),q=h.Math.fixDeckle(f,b);p!=a&&(a=p,c-=1);q!=b&&(b=q,e-=1);this.ctx.translate(a,b);this.ctx.lineWidth=f;this.ctx.strokeStyle=i;o&&(this.ctx.globalCompositeOperation="destination-over");g&&(this.ctx.fillStyle=g);h.isArray(d)?(this.ctx.beginPath(),this.ctx.moveTo(d[0],0),this.ctx.lineTo(c-d[1],0),this.ctx.arcTo(c,
0,c,d[1],d[1]),this.ctx.lineTo(c,e-d[2]),this.ctx.arcTo(c,e,c-d[2],e,d[2]),this.ctx.lineTo(d[3],e),this.ctx.arcTo(0,e,0,e-d[3],d[3]),this.ctx.lineTo(0,d[0]),this.ctx.arcTo(0,0,d[0],0,d[0]),this.ctx.closePath(),this.shadowOn(j,m,k,n,l),g&&this.ctx.fill(),j&&this.shadowOff(),this.ctx.globalCompositeOperation="source-over",this.ctx.stroke()):(this.shadowOn(j,m,k,n,l),g&&this.ctx.fillRect(0,0,c,e),j&&this.shadowOff(),this.ctx.strokeRect(0,0,c,e));this.ctx.restore();return this},toImageURL:function(){return this.canvas.toDataURL("image/png")},
addEvent:function(a,b,c){h.Event.addEvent(this.canvas,a,b,c)}};h.Chart=h.extend(h.Painter,{configure:function(){h.Chart.superclass.configure.apply(this,arguments);this.type="chart";this.set({render:"",data:[],width:void 0,height:void 0,align:"center",segmentRect:!0,title:"",title_align:"center",title_valign:"top",title_writingmode:"lr",title_font:"Verdana",title_fontweight:"bold",title_fontsize:20,title_color:"black",title_height:25,title_lineheight:25,showpercent:!0,decimalsnum:1,animation:!1,doAnimationFn:h.emptyFn,
animation_timing_function:"easeInOut",duration_animation_duration:1600,legend:{enable:!1},tip:{enable:!1}});this.registerEvent("parseData","parseTipText","parseLabelText","beforeAnimation","afterAnimation");this.target=null;this.animationed=this.rendered=!1;this.components=[];this.total=0},pushComponent:function(a,b){h.isArray(a)?this.components=b?a.concat(this.components):this.components.concat(a):b?this.components=[a].concat(this.components):this.components.push(a)},plugin:function(a,b){this.init();
a.inject(this);this.pushComponent(a,b)},toImageURL:function(){return this.target.toImageURL()},segmentRect:function(){this.target.clearRect(this.get("l_originx"),this.get("t_originy"),this.get("client_width"),this.get("client_height"))},resetCanvas:function(){this.target.backgound(this.get("l_originx"),this.get("t_originy"),this.get("client_width"),this.get("client_height"),this.get("background_color"))},animation:function(){return function(a){a.segmentRect();a.doAnimation(a.variable.animation.time,
a.duration);a.resetCanvas();a.variable.animation.time<a.duration?(a.variable.animation.time++,setTimeout(function(){a.animation(a)},h.INTERVAL)):setTimeout(function(){a.variable.animation.time=0;a.animationed=!0;a.draw();a.processAnimation=!1;a.fireEvent(this,"afterAnimation",[this])},h.INTERVAL)}}(),doAnimation:function(a,b){this.get("doAnimationFn").call(this,a,b)},commonDraw:function(){h.Assert.isTrue(this.rendered,this.type+" has not rendered.");h.Assert.isTrue(this.initialization,this.type+" has initialize failed.");
h.Assert.gtZero(this.data.length,this.type+"'data is empty.");this.redraw||(this.title(),this.get("border.enable")?this.target.drawBorder(0,0,this.width,this.height,this.get("border.width"),this.get("border.color"),0==this.get("border.radius")?0:h.Math.parseBorder(this.get("border.radius")),this.get("background_color"),!0):this.target.backgound(0,0,this.width,this.height,this.get("background_color")));this.redraw=!0;if(!this.animationed&&this.get("animation"))this.fireEvent(this,"beforeAnimation",
[this]),this.animation(this);else{this.segmentRect();for(var a=0;a<this.components.length;a++)this.components[a].draw();this.resetCanvas()}},title:function(){""!=this.get("title")&&("tb"!=this.get("title_writingmode")&&("left"==this.get("title_align")?this.push("title_originx",this.get("padding_left")):"right"==this.get("title_align")?this.push("title_originx",this.width-this.get("padding_right")):this.push("title_originx",this.get("client_width")/2),this.target.textAlign(this.get("title_align")),
"bottom"==this.get("title_valign")?this.push("title_originy",this.height-this.get("padding_bottom")):this.push("title_originy",this.get("padding_top")),this.target.textBaseline(this.get("title_valign"))),this.target.textFont(h.getFont(this.get("title_fontweight"),this.get("title_fontsize"),this.get("title_font"))),this.target.fillText(this.get("title"),this.get("title_originx"),this.get("title_originy"),this.get("client_width"),this.get("title_color")))},create:function(a){this.width=this.push("width",
this.get("width")||400);this.height=this.push("height",this.get("height")||300);var b="width:"+this.width+"px;height:"+this.height+"px;padding:0px;overflow:hidden;position:relative;",c=h.Math.iGather(this.type);this.shellid=h.Math.iGather(this.type+"-shell");a.innerHTML="<div id='"+this.shellid+"' style='"+b+"'><canvas id= '"+c+"'  width='"+this.width+"' height="+this.height+"'><p>Your browser does not support the canvas element</p></canvas></div>";this.element=document.getElementById(c);this.shell=
document.getElementById(this.shellid);this.target=new w(this.element);this.rendered=!0},render:function(a){this.push("render",a)},initialize:function(){if(!this.rendered){var a=this.get("render");"string"==typeof a&&document.getElementById(a)?this.create(document.getElementById(a)):"object"==typeof a&&this.create(a)}0<this.get("data").length&&this.rendered&&!this.initialization&&(h.Interface.parser.call(this),this.doConfig(),this.initialization=!0)},doConfig:function(){h.Chart.superclass.doConfig.call(this);
this.get("animation")&&(this.processAnimation=this.get("animation"),this.duration=Math.ceil(this.get("duration_animation_duration")*h.FRAME/1E3),this.variable.animation={time:0},this.animationArithmetic=h.getAnimationArithmetic(this.get("animation_timing_function")));this.is3D()&&h.Interface._3D.call(this);this.target.strokeStyle(this.get("brushsize"),this.get("strokeStyle"),this.get("lineJoin"));var a=this;this.target.addEvent("click",function(b){a.fireEvent(a,"click",[h.Event.fix(b)])},!1);this.target.addEvent("mousemove",
function(b){a.fireEvent(a,"mousemove",[h.Event.fix(b)])},!1);this.on("click",function(a){if(!this.processAnimation)for(var b,c=0;c<this.components.length;c++){b=this.components[c];if(!b.preventEvent){var d=b.isMouseOver(a);d.valid&&this.components[c].fireEvent(b,"click",[a,d])}}});this.on("mousemove",function(a){if(!this.processAnimation){for(var b=false,c=0;c<this.components.length;c++){var d;d=this.components[c];if(!d.preventEvent){var g=d.isMouseOver(a);if(g.valid){b=true;if(!this.variable.event.mouseover){this.variable.event.mouseover=
true;this.target.css("cursor","pointer");this.fireEvent(this,"mouseover",[a])}if(!d.variable.event.mouseover){d.variable.event.mouseover=true;d.fireEvent(d,"mouseover",[a,g])}d.fireEvent(d,"mousemove",[a,g])}else if(d.variable.event.mouseover){d.variable.event.mouseover=false;d.fireEvent(d,"mouseout",[a,g])}}}if(!b&&this.variable.event.mouseover){this.variable.event.mouseover=false;this.target.css("cursor","default");this.fireEvent(this,"mouseout",[a])}}});h.Assert.isArray(this.data);this.push("l_originx",
this.get("padding_left"));this.push("r_originx",this.width-this.get("padding_right"));this.push("t_originy",this.get("padding_top"));this.push("b_originy",this.height-this.get("padding_bottom"));var b=0,c=0;""!=this.get("title")&&("tb"==this.get("title_writingmode")?(b=this.get("title_height"),"left"==this.get("title_align")?this.push("l_originx",this.get("l_originx")+this.get("title_height")):this.push("r_originx",this.width-this.get("l_originx")-this.get("title_height"))):(c=this.get("title_height"),
"left"==this.get("title_align")?this.push("title_originx",this.get("padding_left")):"right"==this.get("title_align")?this.push("title_originx",this.width-this.get("padding_right")):this.push("title_originx",this.get("client_width")/2),"bottom"==this.get("title_valign")?(this.push("title_originy",this.height-this.get("padding_bottom")),this.push("b_originy",this.height-this.get("b_originy")-this.get("title_height"))):(this.push("t_originy",this.get("t_originy")+this.get("title_height")),this.push("title_originy",
this.get("padding_top")))));this.push("client_width",this.get("width")-this.get("padding_left")-this.get("padding_right")-b);this.push("client_height",this.get("height")-this.get("padding_top")-this.get("padding_bottom")-c);this.push("minDistance",Math.min(this.get("client_width"),this.get("client_height")));this.push("maxDistance",Math.max(this.get("client_width"),this.get("client_height")));this.push("minstr",this.get("client_width")<this.get("client_height")?"width":"height");this.push("centerx",
this.get("l_originx")+this.get("client_width")/2);this.push("centery",this.get("t_originy")+this.get("client_height")/2);this.get("border.enable")&&(b=h.Math.parseBorder(this.get("border.radius")),this.push("radius_top",b[0]),this.push("radius_right",b[1]),this.push("radius_bottom",b[2]),this.push("radius_left",b[3]));this.get("legend.enable")&&(this.legend=new h.Legend(h.apply({maxwidth:this.get("client_width"),data:this.data},this.get("legend")),this),this.components.push(this.legend));this.get("tip.enable")&&
this.push("tip.wrap",this.shell)},setData:function(a){this.data=a}})})(iChart);
