iChart.Legend=iChart.extend(iChart.Component,{configure:function(){iChart.Legend.superclass.configure.apply(this,arguments);this.type="legend";this.set({data:void 0,width:"auto",column:1,row:"max",maxwidth:0,line_height:16,sign:"square",sign_size:12,sign_space:5,legendspace:5,text_with_sign_color:!1,align:"right",valign:"middle"});this.registerEvent("drawCell","analysing","drawRaw")},drawCell:function(a,b,f,d){var c=this.get("sign_size");"round"==this.get("sign")?this.target.round(a+c/2,b+c/2,c/2,
d):"round-bar"==this.get("sign")?(this.target.rectangle(a,b+5*c/12,c,c/6,d),this.target.round(a+c/2,b+c/2,c/4,d)):"square-bar"==this.get("sign")?(this.target.rectangle(a,b+5*c/12,c,c/6,d),this.target.rectangle(a+c/4,b+c/4,c/2,c/2,d)):this.target.rectangle(a,b,c,c,d);var g=this.get("color");this.get("text_with_sign_color")&&(g=d);this.target.fillText(f,a+this.get("signwidth"),b+c/2,this.get("textwidth"),g);this.fireEvent(this,"drawCell",[a,b,f,d])},drawRow:function(a,b,f){for(var d=0;d<this.get("column");d++)a<
this.data.length&&(this.fireEvent(this,"drawCell",[this.data[a]]),this.drawCell(b,f,this.data[a].text,this.data[a].color),this.data[a].x=b,this.data[a].y=f),b+=this.columnwidth[d]+this.get("signwidth")+this.get("legendspace"),a++},isEventValid:function(a){if(a.offsetX>this.x&&a.offsetX<this.x+this.get("width")&&a.offsetY>this.y&&a.offsetY<this.y+this.get("height"))for(var b=0;b<this.data.length;b++)if(a.offsetX>this.data[b].x&&a.offsetX<this.data[b].x+this.data[b].width+this.get("signwidth")&&a.offsetY>
this.data[b].y&&a.offsetY<this.data[b].y+this.get("line_height"))return{valid:!0,value:b,target:this.data[b]};return{valid:!1}},doDraw:function(){this.get("border.enable")&&this.target.drawBorder(this.x,this.y,this.width,this.height,this.get("border.width"),this.get("border.color"),0==this.get("border.radius")?0:iChart.parseBorder(this.get("border.radius")),this.get("background_color"),!1,this.get("shadow"),this.get("shadow_color"),this.get("shadow_blur"),this.get("shadow_offsetx"),this.get("shadow_offsety"));
this.target.textStyle("left","middle",iChart.getFont(this.get("fontweight"),this.get("fontsize"),this.get("font")));for(var a=this.x+this.get("padding_left"),b=this.y+this.get("padding_top"),f=this.get("column"),d=this.get("row"),c=0;c<d;c++)this.fireEvent(this,"drawRaw",[c*f]),this.drawRow(c*f,a,b),b+=this.get("line_height")},doEvent:function(){},doConfig:function(){iChart.Legend.superclass.doConfig.call(this);iChart.Assert.isNotEmpty(this.get("data"),this.type+"[data]");this.push("signwidth",this.get("sign_size")+
this.get("sign_space"));this.get("line_height")<this.get("sign_size")&&this.push("line_height",this.get("sign_size")+this.get("sign_size")/5);var a=iChart.isNumber(this.get("column")),b=iChart.isNumber(this.get("row"));!a&&!b&&(a=1);a&&!b&&this.push("row",Math.ceil(this.data.length/this.get("column")));!a&&b&&this.push("column",Math.ceil(this.data.length/this.get("row")));var a=this.get("column"),b=this.get("row"),f=0,d=this.get("width"),c=0,g="auto"==this.get("width");this.columnwidth=Array(a);g&&
(this.target.textFont(this.get("fontStyle")),d=0);for(var e=0;e<this.data.length;e++)iChart.merge(this.data[e],this.fireEvent(this,"analysing",[this.data[e],e])),this.data[e].text=this.data[e].text||this.data[e].name,this.data[e].width=this.target.measureText(this.data[e].text);for(e=0;e<a;e++){c=0;for(f=e;f<this.data.length;)c=Math.max(c,this.data[f].width),f+=a;this.columnwidth[e]=c;d+=c}g&&this.push("width",d+this.get("hpadding")+this.get("signwidth")*a+(a-1)*this.get("legendspace"));this.get("width")>
this.get("maxwidth")&&this.push("width",this.get("maxwidth"));this.push("textwidth",this.get("width")-this.get("hpadding")-this.get("sign_size")-this.get("sign_space"));this.push("height",b*this.get("line_height")+this.get("vpadding"));this.width=this.get("width");this.height=this.get("height");"center"==this.get("align")&&"middle"==this.get("valign")&&this.push("valign","top");"left"==this.getC("align")&&"middle"==this.get("valign")&&this.push("align","right");"top"==this.get("valign")?this.push("originy",
this.getC("t_originy")):"bottom"==this.get("valign")?this.push("originy",this.getC("b_originy")-this.get("height")):this.push("originy",this.getC("centery")-this.get("height")/2);"left"==this.get("align")?this.push("originx",this.getC("l_originx")):"center"==this.get("align")?this.push("originx",this.getC("centerx")-this.get("textwidth")/2):this.push("originx",this.getC("r_originx")-this.get("width"));this.push("originx",this.get("originx")+this.get("offsetx"));this.push("originy",this.get("originy")+
this.get("offsety"));this.x=this.get("originx");this.y=this.get("originy")}});
